package log;

import java.awt.GraphicsConfiguration;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Calendar;

import javax.swing.JTextPane;

import servidor.Servidor;
import servidor.Servidor.Estados;

/**
 * Clase encargada de mostrar la ventana del log del servidor
 *
 * @author Juan G. Pérez Leo
 * @author Cristian Marín Honor
 */
public class LogView extends javax.swing.JFrame {

    private Servidor principal;
    private BufferedReader lector;
    /**
     * Constructor
     * 
     * @param servidor [Servidor] instancia del servidor
     */
    public LogView(Servidor servidor) {
        this.principal = servidor;
        GraphicsConfiguration graphicsConfiguration = this.getGraphicsConfiguration();
        Insets screenInsets = java.awt.Toolkit.getDefaultToolkit().getScreenInsets(graphicsConfiguration);
        Rectangle pantalla = this.getGraphicsConfiguration().getBounds();
        initComponents();
        int posX = pantalla.width - screenInsets.right - this.getWidth() - 5;
        int posY = pantalla.height - screenInsets.bottom - this.getHeight() - 5;
        setLocation(new Point(posX, posY));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        setTitle("Log de sucesos");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 600, 400));
        setFocusCycleRoot(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jTextPane1.setEditable(false);
        jTextPane1.setToolTipText("Log");
        jTextPane1.setFocusCycleRoot(false);
        jTextPane1.setFocusable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Ocultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    /**
     * Método que captura el evento del botón ocultar
     * 
     * @param evt [ActionEvent] evento capturado del botón
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
    }

    /**
     * Método que captura el evento para limpiar la ventana de log
     * 
     * @param evt [ActionEvent] evento capturado del botón
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        limpiar();
    }

    /**
     * Limpia la ventana de log del servidor
     */
    public void limpiar() {
        jTextPane1.setText("");
    }

    /**
     * Lee del fichero log y lo muestra en la ventana de log del servidor
     * 
     * @param estadoEnum [Estados] estado que va a tener el mensaje
     * @param nombre [String] nombre del archivo de log del que va a leer
     * @throws FileNotFoundException excepción lanzada en caso de no encontrar un archivo
     * @throws IOException excepción lanzada si hay problemas al leer
     */
    public void leer(Servidor.Estados estadoEnum, String nombre) throws FileNotFoundException, IOException {
        limpiar();
        String estado ="["+estadoEnum+"]";
        lector = new BufferedReader(new InputStreamReader(new FileInputStream(nombre),"UTF-8"));
        boolean finFichero = false;
        try {
            while (!finFichero) {
                String linea = lector.readLine();
                String datos[] = linea.split(" ");
                String estadoLinea = datos[0].toLowerCase();
                if(estadoLinea.equals(estado) || estado.equals("[todo]")){
                    if(estadoLinea.equals("[error]")){
                        linea = linea;
                    }
                    escribirLinea(linea);
                }
            }
        } catch (NullPointerException | IOException e) {
            finFichero = true;
        }
        lector.close();
    }
    
    /**
     * Escribe una línea en el log del servidor en la pantalla
     * 
     * @param linea [String] línea que se quiere mostrar
     */
    public static void escribirLinea(String linea) {
        jTextPane1.setText( jTextPane1.getText()+linea+"\n" );
    }
    
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextPane jTextPane1;
    
    public JTextPane getjTextPane1() {
        return jTextPane1;
    }

    public void setjTextPane1(JTextPane jTextPane1) {
        this.jTextPane1 = jTextPane1;
    }
    public static void escribirLog(String linea){
    	if(jTextPane1.isVisible()){
    		escribirLinea(linea);
    	}
    }
}